---
title: "Data Manipulation"
author: "Olya Besedina"
data: "9/19/2019"
output: github_document
---
  
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(readxl)
```

## Import Datasets
```{r}

litters_data = read_csv(file = "./data/FAS_litters.csv")
litters_data = janitor::clean_names((litters_data))

pups_data = read_csv(file = "./data/FAS_pups.csv")
pups_data = janitor::clean_names(pups_data)

pull(litters_data, group)
view(litters_data)
```

## Selecting
```{r}
select(litters_data, group, litter_number)
select(litters_data, group, litter_number, gd0_weight)
select(litters_data, group, litter_number, gd0_weight, starts_with("pups"))
select(litters_data,  litter_number, group, gd0_weight)
# order of writting matters

select(litters_data,  litter_number, group, everything())
# litter data numebr, then group then everything esle

select(litters_data, -group)
# if you want everythig, but group

select(litters_data, litter_number, gd0_weight:pups_born_alive)
# will give you litter number and then everything between gd0_weight and pups born alive

select(litters_data, GROUP = group, litter_number)
# rename

rename(litters_data, GROUP = group)
# select selected what i needed and renamed at the same time, rename can only rename

litters_data = select(litters_data, GROUP = group, litter_number)
# now your litters data is only those columns that you selected( group and litters_number)
```

## Filtering 
```{r}
filter(litters_data, group == "Con7")
# logical operator, checks if it is TRUE; keeps rows for which it is TRUE
# "==" asks Are these 2 things equal to each other? 
# "=" sign assigns value to a name

filter(litters_data, gd_of_birth == 20)
# filter for numeric variable

filter(litters_data, gd_of_birth < 20)

filter(litters_data, gd_of_birth >= 20)

filter(litters_data, pups_born_alive < 6, group == "Con7")
# filter for both of these
# "!=" Not equal to, "!" negates the whole statement
# group %in% c("Con7", "Con8") show those for which at least one is true
# 

filter(litters_data, pups_born_alive >=4, pups_born_alive <=6)

filter(litters_data, gd0_weight + gd18_weight < 70)

filter(litters_data, gd0_weight > gd18_weight)

filter(litters_data, is.na(gd0_weight))
# Dont do this, instead use drop_na

drop_na(litters_data, gd0_weight)
```

## Mutate
```{r}
new_df = mutate(
  litters_data, 
  wt_gain = gd18_weight - gd0_weight,
  group = str_to_lower(group))
```

## Arrange
```{r}
arrange(litters_data, pups_born_alive)
arrange(litters_data, desc(pups_born_alive))
arrange(litters_data, pups_born_alive, gd0_weight)
# wihting pups born alive arange them by gd0_weigtt
```

## Pipe

Create a collection of commands
```{r}
litters_data = 
  read_csv("./data/FAS_litters.csv")%>%
  janitor::clean_names() %>% 
  select(-pups_survive) %>% 
  mutate(
    wt_gain = gd18_weight - gd0_weight,
    group = str_to_lower(group)) %>% 
  drop_na(gd0_weight)
```

```{r, eval = FALSE}
litters_data %>% view()

litters_data %>% pull(gd0_weight) %>% mean

```

```{r}
litters_data = 
  read_csv("./data/FAS_litters.csv")%>%
  janitor::clean_names(dat = .) %>% 
  select(.data = .. -pups_survive) %>% 
  lm(gd0_weight ~ gd18_weight, data = .)

```


